# Generated by Django 5.0.6 on 2024-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_created=True)),
                ('nin', models.CharField(max_length=18)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('municipal', models.CharField(max_length=50)),
                ('wilaya', models.CharField(max_length=50)),
                ('payment_code', models.CharField(max_length=10)),
            ],
        ),
    ]
