# Generated by Django 5.0.6 on 2024-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='wilaya',
            field=models.IntegerField(),
        ),
    ]
