# Generated by Django 5.0.6 on 2024-05-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims_transactions', '0002_alter_transactions_wilaya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='email',
        ),
    ]
