# Generated by Django 5.0.6 on 2024-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims_transactions', '0004_alter_transactions_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
