# Generated by Django 5.0.6 on 2024-05-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims_transactions', '0005_transactions_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='file',
            field=models.FileField(default='d', upload_to='transactions/'),
            preserve_default=False,
        ),
    ]
