# Generated by Django 5.0.4 on 2024-05-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims_transactions', '0006_transactions_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='municipal',
        ),
    ]
