# Generated by Django 5.0.4 on 2024-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims_transactions', '0007_remove_transactions_municipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
